hostname: localhost
port: 7000
maxPerPage: 5 # the number of items to display per page
# running mysql locally (comment out)
# db:
#   driver: mysql
#   host: localhost
#   port: 3306
#   user: entrytask
#   password: password
#   net: tcp
#   dbName: itemservicedb

db:
  driver: mysql
  host: itemservice-db
  port: 3306
  user: entrytask
  password: password
  net: tcp
  dbName: itemservicedb

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0
  expire: 600 # in seconds

external:
  shopee:
    getItem:
      endpoint: https://shopee.sg/api/v4/item/get
      method: get