hostname: localhost
port: 7000
maxPerPage: 5 # the number of items to display per page
serviceLabel: itemservice
# running mysql locally (comment out)
# db:
#   driver: mysql
#   host: localhost
#   port: 3306
#   user: entrytask
#   password: password
#   net: tcp
#   dbName: itemservicedb

db:
  driver: mysql
  serviceLabel: itemservice-mysql
  # host: itemservice-db
  # host: localhost
  host: host.docker.internal
  port: 3306
  # port: 3308
  user: entrytask
  password: password
  net: tcp
  dbName: itemservicedb

redis:
  serviceLabel: itemservice-redis
  host: itemservice-cache
  port: 6379
  # port: 6380
  password: ""
  db: 0
  expire: 600 # in seconds

external:
  shopee:
    getItem:
      endpoint: https://shopee.sg/api/v4/item/get
      method: get

prometheus:
  host: localhost
  port: 7001
  endpoint: /metrics
  