version: "3.6"
services:
  # API Gateway
  gateway:
    build: "./gateway"
    ports:
      - "5000:5000"
    networks:
      - frontend
      - backend
    restart: always
  # Reverse Proxy
  app:
    build: "./frontend"
    ports:
      - "80:80"
    depends_on:
      - gateway
      - prometheus
      - grafana
    networks:
      - frontend
    restart: always
  # User Service DB
  # userservice-db:
  #   image: mysql
  #   ports:
  #     - "3307:3306"
  #   volumes:
  #     - userservice-mysql:/var/lib/mysql
  #     - ./services/userService/db/schema:/docker-entrypoint-initdb.d
  #   command: --default-authentication-plugin=mysql_native_password
  #   # restart: always
  #   networks:
  #     - backend
  #   environment:
  #     - MYSQL_ROOT_USER=root
  #     - MYSQL_ROOT_PASSWORD=password
  #     - MYSQL_DATABASE=userservicedb
  #     - MYSQL_USER=entrytask
  #     - MYSQL_PASSWORD=password
  #   healthcheck:
  #     test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD' ]
  #     timeout: 20s
  #     retries: 10
  # User Service
  userservice:
    build: "./services/userService"
    ports:
      - "6000:6000"
      - "6001:6001"
    networks:
      - backend
    depends_on:
    #   - userservice-db
      - prometheus
      - grafana
    restart: always
  itemservice-cache:
    image: redis:6.2-alpine
    networks:
      - backend
    ports:
      - '6380:6379'
    volumes: 
      - itemservice-redis:/data
    restart: always
    # depends_on:
    #   - prometheus
    #   - grafana
  # itemservice-db:
  #   image: mysql
  #   networks:
  #     - backend
  #   ports:
  #     - "3308:3306"
  #   command: --default-authentication-plugin=mysql_native_password
  #   # restart: always
  #   volumes:
  #     - ./services/itemService/db/schema:/docker-entrypoint-initdb.d
  #     - itemservice-mysql:/var/lib/mysql
  #   environment:
  #     - MYSQL_ROOT_USER=root
  #     - MYSQL_ROOT_PASSWORD=password
  #     - MYSQL_DATABASE=itemservicedb
  #     - MYSQL_USER=entrytask
  #     - MYSQL_PASSWORD=password
  #   healthcheck:
  #     test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD' ]
  #     timeout: 20s
  #     retries: 10    
  # Item Service
  itemservice:
    build: "./services/itemService"
    ports:
      - "7000:7000"
      - "7001:7001"
    networks:
      - backend
    depends_on:
      - itemservice-cache
      - prometheus
      - grafana
      # - itemservice-db
    restart: always

  prometheus:
    container_name: prometheus
    hostname: prometheus
    image: prom/prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      # - ./alert_rules.yml:/etc/prometheus/alert_rules.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    # links:
    #   - cadvisor:cadvisor
    #   - alertmanager:alertmanager
    ports:
      - 9090:9090
    # depends_on:
    #   - cadvisor
    networks:
      - monitoring

  node-exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - '^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)'
    ports:
      - 9100:9100
    restart: always
    deploy:
      mode: global
    networks:
      - backend
      - monitoring

  # analyses and exposes resource usage and performance data from running containers
  # cadvisor:
  #   command:
  #   - privileged=true
  #   privileged: true
  #   image: gcr.io/cadvisor/cadvisor
  #   volumes:
  #     - /:/rootfs:ro
  #     - /var/run:/var/run:rw
  #     - /sys:/sys:ro
  #     - /var/lib/docker/:/var/lib/docker:ro
  #   ports:
  #     - 8080:8080
  #   restart: always
  #   deploy:
  #     mode: global

  grafana:
    container_name: grafana
    hostname: grafana
    image: grafana/grafana
    volumes:
      - ./monitoring/grafana_datasources.yml:/etc/grafana/provisioning/datasources/all.yaml
      - ./monitoring/grafana_config.ini:/etc/grafana/config.ini
      - grafana_data:/var/lib/grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    networks:
      - monitoring
  
  # monitors the user service db
  userservice-mysql-exporter:
    container_name: userservice-mysql-exporter
    image: prom/mysqld-exporter:latest
    environment:
      - DATA_SOURCE_NAME=exporter:exporterpassword@(docker.for.mac.host.internal:3306)/itemservicedb
      - web.listen-address=:9104
      - collect.info_schema.tablestats=true
      - collect.info_schema.userstats=true
      - collect.info_schema.query_response_time=true
      - collect.auto_increment.columns=true
      - collect.binlog_size=true
      - collect.perf_schema.eventsstatements=true
      - collect.perf_schema.eventswaits=true
      - collect.perf_schema.file_events=true
      - collect.perf_schema.indexiowaits=true
      - collect.perf_schema.tableiowaits=true
      - collect.perf_schema.tablelocks=true
    ports:
      - 9104:9104
    networks:
      - monitoring

  itemservice-mysql-exporter:
    container_name: itemservice-mysql-exporter
    image: prom/mysqld-exporter:latest
    environment:
      - DATA_SOURCE_NAME=exporter:exporterpassword@(docker.for.mac.host.internal:3306)/itemservicedb
      - web.listen-address=:9105
      - collect.info_schema.tablestats=true
      - collect.info_schema.userstats=true
      - collect.info_schema.query_response_time=true
      - collect.auto_increment.columns=true
      - collect.binlog_size=true
      - collect.perf_schema.eventsstatements=true
      - collect.perf_schema.eventswaits=true
      - collect.perf_schema.file_events=true
      - collect.perf_schema.indexiowaits=true
      - collect.perf_schema.tableiowaits=true
      - collect.perf_schema.tablelocks=true
    ports:
      - 9105:9104
    networks:
      - monitoring

  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:1.37
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true
    ports:
    - 6831:6831/udp
    - 6832:6832/udp
    - 5778:5778
    - 16686:16686
    - 4317:4317
    - 4318:4318
    - 14250:14250
    - 14268:14268
    - 14269:14269
    - 9411:9411
    networks:
    - backend
volumes:
  # userservice-mysql:
  itemservice-redis:
  # itemservice-mysql:
  prometheus_data: {}
  grafana_data: {}

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
  monitoring:
    driver: bridge