hostname: localhost
port: 5000
ginMode: debug
trustedProxies:
  # - http://docker.for.mac.host.internal:80
  - http://app:80
allowedOrigins:
  # - http://docker.for.mac.host.internal:80
  - http://app:80

# config for incoming requests
http:
  userService:
    label: userservice
    secret: zhtq0eMHQpyQSZKV2ILyk2gXphHkMeCbBKNu5Xa5yhLHJwEahhcBWKP9to5WXRF
    expiry: 30 # expiry time for auth cookie in minutes
    urlGroup: /api/user
    apis:
      signup:
        endpoint: /signup
        method: post
      login:
        endpoint: /login
        method: post
    
  itemService:
    label: itemservice
    urlGroup: /api/item
    apis:
      addFav:
        endpoint: /add/fav
        method: post
      deleteFav:
        endpoint: /delete/fav
        method: delete
      getFavList:
        endpoint: /get/list
        method: get

# config for gateway as a grpc client to the respective microservices
grpc:
  userService:
    label: gateway-userservice-client
    # host: localhost
    host: userservice
    port: 6000
  itemService:
    label: gateway-itemservice-client
    # host: localhost
    host: itemservice
    port: 7000

prometheus:
  host: localhost
  port: 5000
  endpoint: /metrics

jaeger:
  host: docker.for.mac.host.internal:6831
  serviceName: gateway
  logSpans: true