hostname: localhost
port: 5000
ginMode: debug
trustedProxies:
  - http://localhost:80
allowedOrigins:
  - http://localhost:80

# config for incoming requests
http:
  userService:
    label: userservice
    host: localhost
    port: 6000
    secret: zhtq0eMHQpyQSZKV2ILyk2gXphHkMeCbBKNu5Xa5yhLHJwEahhcBWKP9to5WXRF
    urlGroup: /api/user
    apis:
      signup:
        endpoint: /signup
        method: post
      login:
        endpoint: /login
        method: post
  itemService:
    label: itemservice
    host: localhost
    port: 7000
    urlGroup: /api/item
    apis:
      addFav:
        endpoint: /add/fav
        method: post
      deleteFav:
        endpoint: /delete/fav
        method: delete
      getFavList:
        endpoint: /get/list
        method: get

# config for routing requests to the different services
grpc:
  userService:
    label: userservice
    # host: localhost
    host: userservice
    port: 6000
  itemService:
    label: itemservice
    # host: localhost
    host: itemservice
    port: 7000

prometheus:
  host: localhost
  port: 5000
  endpoint: /metrics

jaeger:
  host: localhost:6831
  serviceName: gateway
  logSpans: true