package constants

const (
	// UserID string
	UserID = "userID"
	// ItemID string
	ItemID = "itemID"
	// ShopID string
	ShopID = "shopID"
	// Query string
	Query = "query"
	// Count string
	Count = "count"
	// Page string
	Page = "page"
	// Res string
	Res = "res"
	// ID string
	ID = "id"
	// AddUser string
	AddUser = "addUser"
	// GetUserByUsername string
	GetUserByUsername = "getUserByUsername"
	// NilErrorCode string
	NilErrorCode = "-1"
	// ErrorCode string
	ErrorCode = "errorCode"
	// Port string
	Port = "port"
	// Host string
	Host = "host"
	// TCP string
	TCP = "tcp"
	// Insert string
	Insert = "INSERT"
	// Select string
	Select = "SELECT"
	// Delete string
	Delete = "DELETE"
	// OpName string
	OpName = "opName"
	// MySQL string
	MySQL = "mysql"
	// True string
	True = "true"
	// False string
	False = "false"
	// Username string
	Username = "username"
	// Login string
	Login = "login"
	// Signup string
	Signup = "signup"
)
