package constants

const (
	// UserID string
	UserID = "userID"
	// ItemID string
	ItemID = "itemID"
	// ShopID string
	ShopID = "shopID"
	// Query string
	Query = "query"
	// Count string
	Count = "count"
	// Page string
	Page = "page"
	// Res string
	Res = "res"
	// ID string
	ID = "id"
	// DeleteFav string
	DeleteFav = "deleteFav"
	// GetFavList string
	GetFavList = "getFavList"
	// AddFav string
	AddFav = "addFav"
	// GetFavCount string
	GetFavCount = "getFavCount"
	// Item string
	Item = "item"
	// NilErrorCode string
	NilErrorCode = "-1"
	// ErrorCode string
	ErrorCode = "errorCode"
	// Port string
	Port = "port"
	// Host string
	Host = "host"
	// TCP string
	TCP = "tcp"
	// Insert string
	Insert = "INSERT"
	// Select string
	Select = "SELECT"
	// Delete string
	Delete = "DELETE"
	// OpName string
	OpName = "opName"
	// MySQL string
	MySQL = "mysql"
	// True string
	True = "true"
	// False string
	False = "false"
	// Key string
	Key = "key"
	// Bytes string
	Bytes = "bytes"
	// Exp string
	Exp = "exp"
	// Get string
	Get = "GET"
	// Set string
	Set = "SET"
	// Endpoint string
	Endpoint = "endpoint"
)
